USE WarehouseAnalytics;

-- Exploratory Data Analysis (EDA)

-- Warehouse Exploration

-- Exploring objects in warehouse
SELECT *
FROM INFORMATION_SCHEMA.TABLES;

SELECT * FROM dim_customers;
SELECT * FROM dim_products;
SELECT * FROM fact_sales;

-- Exploring columns for all tables in warehouse
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_products';

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'fact_sales';


-- Dimensions Exploration

-- Explore all countries customers come from
SELECT DISTINCT country
FROM dim_customers;

-- Explore all categories and subcategories of products
SELECT DISTINCT category, subcategory, product_name
FROM dim_products
ORDER BY 1,2,3;


-- Date Exploration

-- Find the date of the first and last orders. How many years of sales are available
SELECT 
	MIN(order_date) AS first_order_date, 
	MAX(order_date) AS last_order_date,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM fact_sales;

-- Find the youngest and oldest customers
SELECT 
	MAX(birthdate) AS youngest_date,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age,
	MIN(birthdate) AS oldest_date,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age
FROM dim_customers;


-- Measures Exploration (KPIs)

-- Find the total sales
SELECT SUM(sales_amount) AS total_sales
FROM fact_sales;

-- Find how many items are sold
SELECT SUM(quantity) AS total_items_sold
FROM fact_sales;

-- Find the average selling price
SELECT AVG(price) AS avg_price
FROM fact_sales;

-- Find the total number of orders
SELECT COUNT(DISTINCT order_number) AS num_orders
FROM fact_sales;

-- Find the total number of products
SELECT COUNT(DISTINCT product_name) AS num_products
FROM dim_products;

-- Find the total number of customers
SELECT COUNT (customer_key) AS num_customers
FROM dim_customers;

-- Find the total number of customers that have placed an order
SELECT COUNT (DISTINCT customer_key) AS num_customers_placed_order
FROM fact_sales;


-- Generate a report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Quantity' AS measure_name, SUM(quantity) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM fact_sales
UNION ALL
SELECT 'No. Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM fact_sales
UNION ALL
SELECT 'No. Products' AS measure_name, COUNT(DISTINCT product_name) AS measure_value FROM dim_products
UNION ALL
SELECT 'No. Customers' AS measure_name, COUNT (customer_key) AS measure_value FROM dim_customers;


-- Magnitude Analysis (Measure by Dimension)

-- Find total customers by country
SELECT country, COUNT(customer_key) AS num_customers
FROM dim_customers
GROUP BY country
ORDER BY num_customers DESC;

-- Find total customers by gender
SELECT gender, COUNT(customer_key) AS num_customers
FROM dim_customers
GROUP BY gender
ORDER  BY num_customers DESC;

-- Find total products by catgory
SELECT category, COUNT(product_key) AS num_products
FROM dim_products
GROUP BY category
ORDER BY num_products DESC;

-- What is the average cost in each category
SELECT category, AVG(cost) AS avg_cost
FROM dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT prod.category, SUM(sales_amount) AS total_revenue
FROM fact_sales sal
LEFT JOIN dim_products prod
	ON sal.product_key = prod.product_key
GROUP BY prod.category
ORDER BY total_revenue DESC;

-- Find the total revenue generated by each customer
SELECT cust.customer_key, cust.first_name, cust.last_name, SUM(sales_amount) AS total_revenue
FROM fact_sales sal
LEFT JOIN dim_customers cust
	ON sal.customer_key = cust.customer_key
GROUP BY cust.customer_key, cust.first_name, cust.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT cust.country, SUM(sal.quantity) AS total_sold_items
FROM fact_sales sal
LEFT JOIN dim_customers cust
	ON sal.customer_key = cust.customer_key
GROUP BY cust.country
ORDER BY total_sold_items DESC;


-- Ranking Analysis (Rank dimension by measure)

-- Which 5 products generate the highest revenue?
SELECT TOP 5 
	prod.product_name, 
	SUM(sal.sales_amount) AS total_revenue
FROM fact_sales sal
LEFT JOIN dim_products prod
	ON sal.product_key = prod.product_key
GROUP BY prod.product_name
ORDER BY total_revenue DESC;

-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5 
	prod.product_name, 
	SUM(sal.sales_amount) AS total_revenue
FROM fact_sales sal
LEFT JOIN dim_products prod
	ON sal.product_key = prod.product_key
GROUP BY prod.product_name
ORDER BY total_revenue;

-- Find the top 10 customers who have generated the highest revenue
WITH ranking_CTE AS (
	SELECT 
		CONCAT_WS(' ', cust.first_name, cust.last_name) AS customer_name,
		SUM(sal.sales_amount) AS total_revenue,
		ROW_NUMBER() OVER(ORDER BY SUM(sal.sales_amount) DESC) AS row_rank
	FROM fact_sales sal
	LEFT JOIN dim_customers cust
		ON sal.customer_key = cust.customer_key
	GROUP BY CONCAT_WS(' ', cust.first_name, cust.last_name)
)
SELECT * FROM ranking_CTE WHERE row_rank <= 5 ORDER BY row_rank;

-- Find the 3 customers with the fewest orders placed
SELECT * FROM (
	SELECT 
		CONCAT_WS(' ', cust.first_name, cust.last_name) AS customer_name,
		COUNT(Distinct order_number) AS num_orders,
		ROW_NUMBER() OVER (ORDER BY COUNT(Distinct order_number)) AS row_rank
	FROM fact_sales sal
	LEFT JOIN dim_customers cust
		ON sal.customer_key = cust.customer_key
	GROUP BY CONCAT_WS(' ', cust.first_name, cust.last_name)
) AS ranking_subq
WHERE row_rank <= 3
ORDER BY row_rank;



-- Advanced Data Analytics



-- Change Over Time (Measure by Date)


-- High-level overview of sales performance over years
SELECT 
	YEAR(order_date) AS order_year, 
	SUM(sales_amount) AS total_sales
FROM fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date)
ORDER BY YEAR(order_date);

-- Looking into sales performance seasonality (months)
SELECT 
	MONTH(order_date) AS order_month, 
	SUM(sales_amount) AS total_sales
FROM fact_sales
WHERE order_date IS NOT NULL
GROUP BY MONTH(order_date)
ORDER BY MONTH(order_date);

-- Inspecting sales performance, total customers, and quantity over year-month date
SELECT 
	DATETRUNC(MONTH,order_date) AS order_date, 
	SUM(sales_amount) AS total_sales,
	COUNT(DISTINCT customer_key) AS total_customers,
	SUM(quantity) AS total_quantity
FROM fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH,order_date)
ORDER BY DATETRUNC(MONTH,order_date);


-- Cumulative Analysis (Cumulative measure by date)


-- Calculate the total sales per month and the running total of sales over time in each year
SELECT
	order_date, 
	total_sales,
	SUM(total_sales) OVER(PARTITION BY YEAR(order_date) ORDER BY order_date) AS sales_running_total,
	AVG(avg_price) OVER(PARTITION BY YEAR(order_date) ORDER BY order_date) AS price_moving_average
FROM (
		SELECT 
			DATETRUNC(MONTH, order_date) AS order_date, 
			SUM(sales_amount) AS total_sales,
			AVG(price) AS avg_price
		FROM fact_sales
		WHERE order_date IS NOT NULL
		GROUP BY DATETRUNC(MONTH, order_date)
	) AS subq
ORDER BY order_date;


--  Performance Analysis (Current measure - target measure)

-- Analyze the yearly performance of products by comparing each product's sales 
-- to both its average sales performance and the previous year's sales (yoy analysis)
WITH yearly_product_sales AS (
	SELECT 
		YEAR(sal.order_date) AS order_year, 
		prod.product_name, 
		SUM(sal.sales_amount) AS current_sales
	FROM fact_sales sal
	LEFT JOIN dim_products prod
		ON sal.product_key = prod.product_key
	GROUP BY prod.product_name, YEAR(sal.order_date) 
)
SELECT 
	order_year, 
	product_name, 
	current_sales,
	AVG(current_sales) OVER(PARTITION BY product_name) AS avg_sales,
	current_sales - AVG(current_sales) OVER(PARTITION BY product_name) AS diff_avg,
	CASE 
		WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) > 0 THEN 'Above Avg'
		WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) < 0 THEN 'Below Avg'
		ELSE 'Avg'
	END AS avg_change,
	LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) AS prev_year_sales,
	current_sales - LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) AS diff_prev_year,
	CASE 
		WHEN current_sales - LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) > 0 THEN 'Increase'
		WHEN current_sales - LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) < 0 THEN 'Decrease'
		ELSE 'No Change'
	END AS prev_year_change
FROM yearly_product_sales
ORDER BY product_name, order_year;


-- Part-to-Whole Analysis ( (Measure/Total Measure)*100 By Dimension )

-- Which categories contribute most to overall sales
WITH sales_per_category AS (
	SELECT prod.category, SUM(sal.sales_amount) AS total_sales
	FROM fact_sales sal
	LEFT JOIN dim_products prod
		ON sal.product_key = prod.product_key
	GROUP BY prod.category
)
SELECT
	category,
	total_sales,
	SUM(total_sales) OVER() AS overall_sales,
	CONCAT(ROUND((CAST(total_sales AS FLOAT)/SUM(total_sales) OVER())*100,2), '%') AS percentage_of_total
FROM sales_per_category
ORDER BY total_sales DESC;


-- Data Segmentation (Measure by Measure categorized)

-- Segment products into cost ranges and count how many products fall into each segment
WITH product_segments AS (
	SELECT 
		product_key, 
		product_name,
		CASE 
			WHEN cost < 100 THEN 'Below 100'
			WHEN cost > 100 AND cost < 500 THEN '100-500'
			WHEN cost > 500 AND cost < 1000 THEN '500-1000'
			ELSE 'Above 1000'
		END AS cost_range
	FROM dim_products
)
SELECT
	cost_range,
	COUNT(product_key) AS total_products
FROM product_segments
GROUP BY cost_range
ORDER BY total_products DESC;


-- Group customers into 3 segments based on their spending behaviour:
-- VIP: Customers with at least 12 months history and spending more than 5000
-- Regular: CUstomers with at least 12 months history but spending 5000 or less
-- New: Customers with less than 12 months history
-- Find the total number of customers by each group

WITH customer_spending AS (
SELECT 
	customer_key, 
	SUM(sales_amount) AS total_sales,
	MIN(order_date) AS first_order,
	MAX(order_date) AS last_order,
	DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan
FROM fact_sales
GROUP BY customer_key
),
customer_tiers AS (
SELECT
	customer_key,
	CASE
		WHEN lifespan >= 12 AND total_sales > 5000 THEN 'VIP'
		WHEN lifespan >= 12 AND total_sales <= 5000 THEN 'Regular'
		ELSE 'New'
	END AS customer_tier
FROM customer_spending
)
SELECT
	customer_tier,
	COUNT(customer_key) AS total_customers
FROM customer_tiers
GROUP BY customer_tier
ORDER BY total_customers DESC;



